version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - echo $CODEBUILD_SRC_DIR

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
